'use strict';
const $=id=>document.getElementById(id),token=new URLSearchParams(location.search).get('mesa'),money=c=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let csrf='',user=null,bars=[],barId='',menu=null,cart={},lastIds=new Set(),sound=null,requestId=null;
function note(message){$('message').textContent=message}
async function api(path,method='GET',body){const response=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível concluir.');return data}
function element(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function button(text,callback){const e=element('button',text);e.onclick=()=>Promise.resolve(callback()).catch(error=>note(error.message));return e}
async function bindForm(id,fn){$(id).onsubmit=async event=>{event.preventDefault();note('');try{await fn()}catch(error){note(error.message)}}}
async function photoData(file){if(!file)return null;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10000000)throw Error('Escolha uma foto JPG, PNG ou WebP de até 10 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.85)}
function imageNotice(state){return state==='missing'?'Produto salvo. Não foi encontrada uma foto compatível; use Escolher foto ou tente buscar novamente.':'Produto salvo com imagem no cardápio.'}
function chooseProductPhoto(p){const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.onchange=async()=>{try{const photo=await photoData(input.files[0]);if(!photo)return;await api('/api/bars/'+barId+'/products/'+p.id+'/image','POST',{photo});await loadBar();note('Foto atualizada no cardápio.')}catch(error){note(error.message)}};input.click()}
async function start(){const identity=await api('/api/session');csrf=identity.csrf;user=identity.user;if(token){$('login').hidden=true;$('guest').hidden=false;await loadMenu();return}if(user){$('login').hidden=true;$('staff').hidden=false;$('owner').hidden=user.role!=='owner';$('staffTitle').textContent=user.role==='owner'?'Administração BarZap':'Painel do bar';await loadBars()}}
async function loadBars(){bars=(await api('/api/bars')).bars;const select=$('barSelect');select.replaceChildren();bars.forEach(b=>{const option=element('option','#'+b.release+' • '+b.name);option.value=b.id;select.append(option)});if(!bars.some(b=>b.id===barId))barId=bars[0]?.id||'';select.value=barId;lastIds=new Set();if(barId)await loadBar()}
async function loadBar(){const b=bars.find(b=>b.id===barId);$('subscription').textContent=b.status+' • Início '+b.start+' • Vencimento '+b.due+' • Bloqueio '+b.block;$('trialNotice').textContent=b.notice||'';const [products,tables,orders]=await Promise.all([api('/api/bars/'+barId+'/products'),api('/api/bars/'+barId+'/tables'),api('/api/bars/'+barId+'/orders')]);$('products').replaceChildren();products.products.forEach(p=>{const row=element('p',p.category+' • '+p.name+' • '+(p.price_pending?'Preço pendente':money(p.price_cents)));row.className='catalog-row';const priceInput=element('input','');priceInput.type='number';priceInput.min='0.01';priceInput.step='0.01';priceInput.placeholder='Preço (R$)';priceInput.setAttribute('aria-label','Preço de '+p.name);priceInput.value=p.price_pending?'':(p.price_cents/100).toFixed(2);row.append(priceInput,button('Salvar preço',async()=>{await api('/api/bars/'+barId+'/products/'+p.id+'/price','POST',{price:priceInput.value});await loadBar();note('Preço salvo. Produto disponível no cardápio.')}));if(p.image){const photo=element('img','');photo.src=p.image.url;photo.alt=p.image.alt;photo.className='product-thumb';photo.loading='lazy';row.prepend(photo)}row.append(button('Editar produto',()=>openProductEditor(p)));row.append(button(p.image?'Trocar foto':'Escolher foto',()=>chooseProductPhoto(p)));if(!p.image)row.append(button('Buscar imagem',async()=>{note('Buscando imagem...');const result=await api('/api/bars/'+barId+'/products/'+p.id+'/image','POST',{});await loadBar();note(imageNotice(result.image_state))}));row.append(button('Excluir',async()=>{await api('/api/bars/'+barId+'/products/'+p.id,'DELETE');await loadBar()}));$('products').append(row)});$('tables').replaceChildren();tables.tables.forEach(t=>{const row=element('p','Mesa '+t.name+' • '+(t.open?'Disponível':'Fechada'));if(!t.open)row.append(button('Abrir mesa',async()=>{await api('/api/bars/'+barId+'/tables/'+t.id+'/open','POST',{});await loadBar()}));const link=element('a','Abrir atendimento');link.href=t.link;link.target='_blank';link.rel='noopener';row.append(link);$('tables').append(row)});renderOrders(orders.orders,false);await refreshFinance();renderQrTables(tables.tables)}
function chime(){if(!sound||sound.state!=='running')return;[1318,1568,2093].forEach((frequency,i)=>{const oscillator=sound.createOscillator(),gain=sound.createGain(),at=sound.currentTime+i*.09;oscillator.type='triangle';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.1,at);gain.gain.exponentialRampToValueAtTime(.0001,at+.5);oscillator.connect(gain);gain.connect(sound.destination);oscillator.start(at);oscillator.stop(at+.5)})}
function renderOrders(list,notify){const fresh=list.filter(o=>!lastIds.has(o.id));if(notify&&fresh.length)chime();lastIds=new Set(list.map(o=>o.id));$('orders').replaceChildren();list.forEach(o=>{const card=element('div','Mesa '+o.table+' • '+o.name+' • '+o.phone+' • '+money(o.total_cents));card.className='card';o.items.forEach(i=>card.append(element('p',i.quantity+' × '+i.name)));card.append(button(o.status+' → Avançar',async()=>{await api('/api/bars/'+barId+'/orders/'+o.id+'/advance','POST',{});await poll()}));$('orders').append(card)})}
async function poll(){if(!user||!barId||token)return;try{const selected=barId;const data=await api('/api/bars/'+selected+'/orders');if(selected===barId){renderOrders(data.orders,true);await refreshFinance()}}catch(error){note(error.message)}}
async function loadMenu(){menu=await api('/api/public/'+encodeURIComponent(token));$('guestBar').textContent=menu.bar;$('guestTable').textContent='Mesa '+menu.table+' • '+(menu.open?'Disponível':'Fechada')+' • Garçom: '+menu.waiter;const saved=JSON.parse(localStorage.getItem('barzap-guest:'+token)||'null');if(saved&&saved.session===menu.session){$('guestName').value=saved.name;$('guestPhone').value=saved.phone}$('menu').replaceChildren();menu.products.forEach(p=>{const card=element('div','');card.className='card menu-product';if(p.image){const photo=element('img','');photo.src=p.image.url;photo.alt=p.image.alt;photo.className='menu-photo '+p.image.kind;photo.loading='lazy';photo.onerror=()=>{photo.hidden=true};card.append(photo)}else{const placeholder=element('div','Foto ainda não disponível');placeholder.className='menu-photo photo-missing';card.append(placeholder)}card.append(element('small',p.category),element('h3',p.name),element('strong',money(p.price_cents)));if(p.image){const info=element('details',''),summary=element('summary','Imagem ilustrativa • créditos');info.className='image-credit';info.append(summary);if(p.image.source){const source=element('a',p.image.credit);source.href=p.image.source;source.target='_blank';source.rel='noopener noreferrer';info.append(source)}else{info.append(element('span',p.image.credit))}if(p.image.license){const license=element('a','Licença da foto');license.href=p.image.license;license.target='_blank';license.rel='noopener noreferrer';info.append(license,element('span','Foto redimensionada; enquadramento ajustado na tela.'))}card.append(info)}card.append(button('Adicionar',()=>{if(!menu.open)throw Error('Mesa fechada.');cart[p.id]=(cart[p.id]||0)+1;requestId=null;renderCart()}));$('menu').append(card)})}
function renderCart(){$('cart').replaceChildren();let total=0;menu.products.forEach(p=>{if(!cart[p.id])return;total+=p.price_cents*cart[p.id];const row=element('p',cart[p.id]+' × '+p.name);row.append(button('Remover',()=>{cart[p.id]--;requestId=null;renderCart()}));$('cart').append(row)});$('cart').append(element('strong','Total '+money(total)))}
bindForm('loginForm',async()=>{const result=await api('/api/login','POST',{email:$('email').value,password:$('password').value});$('password').value='';csrf=result.csrf;user=result.user;await start()});
bindForm('barForm',async()=>{await api('/api/bars','POST',{name:$('barName').value,email:$('barEmail').value,password:$('barPassword').value,plan:$('barPlan').value});$('barPassword').value='';await loadBars()});
bindForm('productForm',async()=>{if(!barId)throw Error('Selecione um bar.');const submit=$('productForm').querySelector('button');submit.disabled=true;try{note('Cadastrando produto e buscando imagem...');const photo=await photoData($('productPhoto').files[0]);const result=await api('/api/bars/'+barId+'/products','POST',{category:$('category').value,name:$('productName').value,price:$('price').value,...(photo?{photo}:{})});$('productForm').reset();await loadBar();note(imageNotice(result.image_state))}finally{submit.disabled=false}});
bindForm('tableForm',async()=>{await api('/api/bars/'+barId+'/tables','POST',{name:$('tableName').value});await loadBar()});
$('barSelect').onchange=async()=>{barId=$('barSelect').value;lastIds=new Set();try{await loadBar()}catch(error){note(error.message)}};
$('logout').onclick=async()=>{try{await api('/api/logout','POST',{});location.assign('/')}catch(error){note(error.message)}};
$('openTables').onclick=async()=>{try{await api('/api/bars/'+barId+'/tables/open','POST',{});await loadBar()}catch(error){note(error.message)}};
$('enableSound').onclick=async()=>{try{sound=new AudioContext();await sound.resume();chime();$('enableSound').textContent='Som ativado'}catch{note('Áudio indisponível neste navegador.')}};
$('sendOrder').onclick=async()=>{const send=$('sendOrder');send.disabled=true;try{if(!requestId)requestId=crypto.randomUUID();const result=await api('/api/public/'+encodeURIComponent(token)+'/orders','POST',{name:$('guestName').value,phone:$('guestPhone').value,note:$('guestNote').value,request_id:requestId,items:Object.entries(cart).filter(([id,q])=>q>0).map(([id,quantity])=>({id,quantity}))});localStorage.setItem('barzap-guest:'+token,JSON.stringify({session:menu.session,name:$('guestName').value,phone:$('guestPhone').value}));cart={};requestId=null;renderCart();note('Pedido enviado. Total: '+money(result.total_cents))}catch(error){note(error.message)}finally{send.disabled=false}};
start().catch(error=>note(error.message));setInterval(poll,3000);


let editingProduct=null;
function openProductEditor(product){editingProduct={id:product.id,bar:barId};$('editProductCategory').value=product.category;$('editProductName').value=product.name;$('editProductPrice').value=product.price_pending?'':(product.price_cents/100).toFixed(2);$('editProductPrice').required=!product.price_pending;$('editProductHint').textContent=product.price_pending?'Você pode deixar o preço vazio e informar depois.':'O novo preço será aplicado aos próximos pedidos.';$('editProductError').textContent='';$('productEditor').showModal()}
$('cancelProductEdit').onclick=()=>{$('productEditor').close();editingProduct=null};
$('editProductForm').onsubmit=async event=>{event.preventDefault();if(!editingProduct)return;const editing={...editingProduct};$('saveProductEdit').disabled=true;$('editProductError').textContent='';try{await api('/api/bars/'+editing.bar+'/products/'+editing.id,'PATCH',{category:$('editProductCategory').value,name:$('editProductName').value,price:$('editProductPrice').value});$('productEditor').close();editingProduct=null;await loadBar();note('Produto atualizado.')}catch(error){$('editProductError').textContent=error.message}finally{$('saveProductEdit').disabled=false}};
