'use strict';
let currentTabs=[],cashState=null,waiterList=[],settlingTab=null,paymentLines=[];
const finPath=path=>'/api/bars/'+barId+'/'+path;
const localTime=value=>value?new Date(value).toLocaleString('pt-BR'):'—';
function inputCents(value){const n=Number(String(value).replace(',','.'));if(!Number.isFinite(n)||n<0||Math.abs(n*100-Math.round(n*100))>.00001)throw Error('Informe um valor válido com até duas casas decimais.');return Math.round(n*100)}
function switchPanel(name){document.querySelectorAll('[data-panel]').forEach(e=>e.hidden=e.dataset.panel!==name);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('selected',e.dataset.tab===name));$('reportFilters').hidden=!['closed','reports'].includes(name)}
async function refreshFinance(){if(!barId)return;const selected=barId;const [cash,tabs,waiters]=await Promise.all([api(finPath('cash')),api(finPath('tabs')),api(finPath('waiters'))]);if(selected!==barId)return;cashState=cash.cash;currentTabs=tabs.tabs;waiterList=waiters.waiters;renderFinance()}
function renderFinance(){
 $('cashState').textContent=cashState?'Caixa aberto em '+localTime(cashState.opened_at)+' • Troco inicial '+money(cashState.opening_cents)+' • Dinheiro esperado '+money(cashState.expected_cash_cents):'Caixa fechado';
 $('cashOpenForm').hidden=!!cashState;$('cashCloseForm').hidden=!cashState;
 $('openTabs').replaceChildren();currentTabs.forEach(t=>{const card=element('div','Mesa '+t.table+' • '+t.waiter);card.className='card';card.append(element('p','Aberta em '+localTime(t.opened_at)+' • Consumo '+money(t.subtotal_cents)));
 const select=document.createElement('select');select.setAttribute('aria-label','Garçom da mesa '+t.table);let empty=element('option','Selecione o garçom');empty.value='';select.append(empty);waiterList.forEach(w=>{const option=element('option',w.name);option.value=w.id;select.append(option)});select.value=t.waiter_id||'';
 select.onchange=async()=>{if(!select.value)return;try{await api(finPath('tables/'+t.table_id+'/waiter'),'POST',{waiter_id:select.value});await refreshFinance()}catch(e){note(e.message)}};card.append(select);
 card.append(button('Receber / fechar comanda',()=>openSettlement(t)));$('openTabs').append(card)});
 if(!currentTabs.length)$('openTabs').append(element('p','Nenhuma comanda aberta.'));
 $('waiterList').replaceChildren();waiterList.forEach(w=>$('waiterList').append(element('p',w.name)));
 $('cashBreakdown').replaceChildren();if(cashState){Object.entries(cashState.methods).forEach(([method,value])=>$('cashBreakdown').append(element('p',method+': '+money(value))));$('cashBreakdown').append(element('p','10% recebidos: '+money(cashState.service_cents)))}
}
function openSettlement(t){if(!cashState)throw Error('Abra o caixa primeiro.');settlingTab=t;paymentLines=[];$('settlementTitle').textContent='Receber mesa '+t.table;$('settlementOpened').textContent='Abertura: '+localTime(t.opened_at)+' • Garçom: '+t.waiter;$('serviceFee').checked=false;$('settlementItems').replaceChildren();t.orders.forEach(o=>o.items.forEach(i=>$('settlementItems').append(element('p',i.quantity+' × '+i.name+' • '+money(i.quantity*i.unit_cents)))));renderPayments();$('settlement').showModal()}
function settlementTotal(){return settlingTab.subtotal_cents+($('serviceFee').checked?Math.floor((settlingTab.subtotal_cents+5)/10):0)}
function renderPayments(){if(!settlingTab)return;const total=settlementTotal(),paid=paymentLines.reduce((s,p)=>s+p.amount_cents,0);$('settlementTotal').textContent='Consumo '+money(settlingTab.subtotal_cents)+' • 10% opcionais '+money(total-settlingTab.subtotal_cents)+' • Total '+money(total);$('paymentRemaining').textContent='Falta receber: '+money(total-paid);$('paymentAmount').value=(Math.max(0,total-paid)/100).toFixed(2);$('paymentList').replaceChildren();paymentLines.forEach((p,i)=>{const row=element('p',(p.person||'Pagamento '+(i+1))+' • '+p.method+' • '+money(p.amount_cents));row.append(button('Remover',()=>{paymentLines.splice(i,1);renderPayments()}));$('paymentList').append(row)});$('confirmSettlement').disabled=paid!==total}
bindForm('paymentForm',async()=>{const amount=inputCents($('paymentAmount').value);if(!amount)throw Error('Informe um valor maior que zero.');paymentLines.push({person:$('paymentPerson').value,method:$('paymentMethod').value,amount_cents:amount});$('paymentPerson').value='';renderPayments()});
$('serviceFee').onchange=renderPayments;$('cancelSettlement').onclick=()=>$('settlement').close();
$('confirmSettlement').onclick=async()=>{const b=$('confirmSettlement');b.disabled=true;try{const result=await api(finPath('tables/'+settlingTab.table_id+'/settle'),'POST',{session:settlingTab.session,service:$('serviceFee').checked,payments:paymentLines});$('settlement').close();await loadBar();await refreshFinance();note('Comanda recebida e fechada. A impressão está na aba Comandas fechadas.')}catch(e){note(e.message)}finally{b.disabled=false}};
bindForm('cashOpenForm',async()=>{if(!barId)throw Error('Selecione um bar.');sound=sound||new AudioContext();await sound.resume();await api(finPath('cash/open'),'POST',{opening_cents:inputCents($('openingFloat').value)});chime();await loadBar();await refreshFinance()});
bindForm('cashCloseForm',async()=>{const password=$('closeOwnerPassword').value;try{await api(finPath('cash/close'),'POST',{counted_cash_cents:inputCents($('countedCash').value),owner_password:password,reason:$('closeReason').value});await refreshFinance();await loadBar();note('Caixa fechado. Consulte a aba Fechamentos de caixa.')}finally{$('closeOwnerPassword').value=''}});
bindForm('waiterForm',async()=>{await api(finPath('waiters'),'POST',{name:$('waiterName').value});$('waiterName').value='';await refreshFinance()});
function printContent(title,build){const root=$('printArea');root.replaceChildren(element('h1',title));build(root);document.body.classList.add('printing');window.print();document.body.classList.remove('printing')}
function printReceipt(r){printContent(r.bar+' — Comanda da mesa '+r.table,root=>{root.append(element('p','Garçom: '+r.waiter),element('p','Abertura: '+localTime(r.opened_at)),element('p','Fechamento: '+localTime(r.closed_at)));r.orders.forEach(o=>{root.append(element('h3',o.name));o.items.forEach(i=>root.append(element('p',i.quantity+' × '+i.name+' • '+money(i.quantity*i.unit_cents))))});root.append(element('p','Consumo: '+money(r.subtotal_cents)),element('p','10% opcionais: '+money(r.service_cents)),element('h2','Total: '+money(r.total_cents)));r.payments.forEach(p=>root.append(element('p',(p.person||'Pagamento')+' • '+p.method+' • '+money(p.amount_cents))))})}
function renderCashReport(c,root){root.append(element('h3','Caixa aberto em '+localTime(c.opened_at)),element('p','Fechado em '+localTime(c.closed_at)),element('p','Troco inicial: '+money(c.opening_cents)));Object.entries(c.methods).forEach(([k,v])=>root.append(element('p',k+': '+money(v))));root.append(element('p','10% recebidos: '+money(c.service_cents)));Object.entries(c.waiters).forEach(([k,v])=>root.append(element('p',k+': '+money(v))));root.append(element('p','Dinheiro esperado: '+money(c.expected_cash_cents)),element('p','Dinheiro contado: '+money(c.closing.counted_cash_cents)),element('p','Diferença: '+money(c.closing.difference_cents)));if(c.closing.pending.length){root.append(element('p','Fechamento autorizado por '+c.closing.authorized_by+' • '+c.closing.reason));c.closing.pending.forEach(t=>root.append(element('p','Pendente: mesa '+t.table+' • '+money(t.subtotal_cents))))}}
async function loadReports(){if(!barId)throw Error('Selecione um bar.');const query=new URLSearchParams({start:$('reportStart').value,end:$('reportEnd').value});const report=await api(finPath('reports?'+query));$('closedTabsReport').replaceChildren();report.receipts.forEach(r=>{const card=element('div','Mesa '+r.table+' • '+localTime(r.closed_at)+' • '+money(r.total_cents));card.className='card';card.append(element('p','Garçom '+r.waiter+' • 10% '+money(r.service_cents)),button('Imprimir comanda',()=>printReceipt(r)));$('closedTabsReport').append(card)});$('cashReports').replaceChildren();report.cash.forEach(c=>{const card=element('div','');card.className='card';renderCashReport(c,card);card.append(button('Imprimir fechamento',()=>printContent(bars.find(b=>b.id===barId).name+' — Fechamento de caixa',root=>renderCashReport(c,root))));$('cashReports').append(card)});if(!report.receipts.length)$('closedTabsReport').append(element('p','Nenhuma comanda fechada neste período.'));if(!report.cash.length)$('cashReports').append(element('p','Nenhum caixa fechado neste período.'))}
$('filterReports').onclick=()=>loadReports().catch(e=>note(e.message));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{switchPanel(b.dataset.tab);if(['closed','reports'].includes(b.dataset.tab))loadReports().catch(e=>note(e.message))});
switchPanel('attendance');
function renderQrTables(tables){$('qrTables').replaceChildren();tables.forEach(t=>{const label=element('label','Mesa '+t.name);label.className='qr-choice';const check=document.createElement('input');check.type='checkbox';check.value=t.id;label.prepend(check);$('qrTables').append(label)})}
$('create50Tables').onclick=async()=>{try{if(!barId)throw Error('Selecione um bar.');await api(finPath('tables/batch'),'POST',{});await loadBar();note('Mesas de 1 a 50 cadastradas.')}catch(e){note(e.message)}};
$('downloadQr').onclick=()=>{const chosen=[...$('qrTables').querySelectorAll('input:checked')].map(e=>e.value);if(!chosen.length){note('Selecione pelo menos uma mesa.');return}const query=new URLSearchParams();chosen.forEach(id=>query.append('table',id));const link=document.createElement('a');link.href=finPath('qr.pdf?'+query);link.download='BarZap-mesas.pdf';link.click()};

