"use strict";
let stockItems=[],stockEditing=false;
async function loadStock(preserve=false){if(!barId)return;const selected=barId;const result=await api('/api/bars/'+selected+'/stock');if(selected!==barId)return;stockItems=result.items;if(!preserve||!stockEditing)renderStockItems();$('purchaseSuggestions').replaceChildren();if(!result.suggestions.length)$('purchaseSuggestions').append(element('p','Nenhum produto com estoque informado abaixo de 6 unidades.'));result.suggestions.forEach(p=>{const row=element('p',p.category+' • '+p.name+' — Estoque: '+p.quantity+' • Comprar: '+p.buy_quantity+' unidade(s)');row.className='stock-low';$('purchaseSuggestions').append(row)});$('stockMovements').replaceChildren();result.movements.forEach(m=>$('stockMovements').append(element('p',new Date(m.created_at).toLocaleString('pt-BR')+' • '+m.name+' • '+m.kind+' '+(m.change>0?'+':'')+m.change+' • Saldo '+m.balance+' • '+m.reason)))}
function renderStockItems(){const search=$('stockSearch').value.toLocaleLowerCase('pt-BR');$('stockItems').replaceChildren();stockItems.filter(p=>(p.name+' '+p.category).toLocaleLowerCase('pt-BR').includes(search)).forEach(p=>{const card=element('div','');card.className='card stock-card';card.append(element('strong',p.name),element('p',p.category+' • Estoque: '+(p.quantity===null?'Não informado':p.quantity+' unidade(s)')));const form=element('form','');form.oninput=()=>{stockEditing=true};const mode=element('select','');mode.setAttribute('aria-label','Operação de estoque de '+p.name);[['count','Definir quantidade atual'],['entry','Registrar entrada de compra']].forEach(([value,name])=>{const option=element('option',name);option.value=value;mode.append(option)});const quantity=element('input','');quantity.type='number';quantity.min='0';quantity.max='1000000';quantity.step='1';quantity.required=true;quantity.placeholder='Quantidade';quantity.setAttribute('aria-label','Quantidade de '+p.name);const reason=element('input','');reason.placeholder='Motivo ou fornecedor';reason.maxLength=200;reason.required=true;reason.setAttribute('aria-label','Motivo de estoque de '+p.name);const save=element('button','Salvar estoque');form.append(mode,quantity,reason,save);form.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{await api('/api/bars/'+barId+'/stock/'+p.id,'POST',{mode:mode.value,quantity:Number(quantity.value),reason:reason.value});stockEditing=false;await loadStock();note('Estoque atualizado.')}catch(error){note(error.message)}finally{save.disabled=false}};card.append(form);$('stockItems').append(card)})}
$('stockSearch').oninput=renderStockItems;
$('refreshStock').onclick=()=>loadStock().catch(e=>note(e.message));
document.querySelector('[data-tab="stock"]').onclick=()=>{switchPanel('stock');loadStock().catch(e=>note(e.message))};
$('barSelect').addEventListener('change',()=>{stockItems=[];stockEditing=false;$('stockSearch').value='';if(!document.querySelector('[data-panel="stock"]').hidden)loadStock().catch(e=>note(e.message))});

setInterval(()=>{if(user&&barId&&!token&&!document.querySelector('[data-panel="stock"]').hidden)loadStock(true).catch(e=>note(e.message))},15000);
